name: mobile_cdv
description: CDV mobile app

flutter:
  uses-material-design: true
  assets:
    - assets/locale/locale.csv
    - assets/images/logo_t.png
    - assets/images/logo-text.png

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Additional logic
  http: ^0.13.4
  jwt_decode: ^0.3.1
  csv: ^5.0.1

  # Storing data
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9

  # Frontend
  table_calendar: ^3.0.4
  flutter_local_notifications: ^9.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0